#!/bin/bash

# VersionZero Theme Switcher
# Cycles through: Midnight → Ocean → Cyberpunk → Midnight
# Usage: ./theme-switcher.sh [theme1|theme2|theme3|next]

CONFIG_DIR="$HOME/.config"
THEME_DIR="$CONFIG_DIR/colors"
CURRENT_THEME_FILE="$THEME_DIR/current-theme"

# Notification function
notify() {
    notify-send -u normal -t 3000 "VersionZero Theme" "$1"
}

# Get current theme
get_current_theme() {
    if [[ -f "$CURRENT_THEME_FILE" ]]; then
        cat "$CURRENT_THEME_FILE"
    else
        echo "theme1"
    fi
}

# Get next theme in cycle
get_next_theme() {
    local current=$(get_current_theme)
    case "$current" in
        theme1) echo "theme2" ;;
        theme2) echo "theme3" ;;
        theme3) echo "theme1" ;;
        *) echo "theme1" ;;
    esac
}

# Apply theme
apply_theme() {
    local theme=$1
    
    # Validate theme
    if [[ ! "$theme" =~ ^theme[1-3]$ ]]; then
        echo "Invalid theme: $theme"
        echo "Valid themes: theme1, theme2, theme3"
        exit 1
    fi
    
    # Source theme file
    if [[ ! -f "$THEME_DIR/$theme.conf" ]]; then
        echo "Theme file not found: $THEME_DIR/$theme.conf"
        exit 1
    fi
    
    source "$THEME_DIR/$theme.conf"
    
    # Save current theme
    echo "$theme" > "$CURRENT_THEME_FILE"
    
    # Apply to Hyprland
    if pidof -x Hyprland > /dev/null; then
        # Reload Hyprland colors
        hyprctl keyword general:col.active_border "$VZ_HYPR_BORDER_ACTIVE"
        hyprctl keyword general:col.inactive_border "$VZ_HYPR_BORDER_INACTIVE"
    fi
    
    # Reload Waybar (only if running)
    if pidof -x waybar > /dev/null 2>&1; then
        # Generate waybar CSS with current theme
        generate_waybar_css "$theme"
        pkill -SIGUSR2 waybar 2>/dev/null
    fi
    
    # Reload EWW (only if running)
    if pidof -x eww > /dev/null 2>&1; then
        # Generate EWW SCSS with current theme
        generate_eww_css "$theme"
        eww reload 2>/dev/null
    fi
    
    # Reload Mako (only if running)
    if pidof -x mako > /dev/null 2>&1; then
        generate_mako_config "$theme"
        makoctl reload 2>/dev/null
    fi
    
    # Update terminal configs (will apply on next launch)
    generate_terminal_configs "$theme"
    
    # Notify user
    notify "Theme changed to: $VZ_THEME_NAME"
    
    echo "✓ Theme applied: $VZ_THEME_NAME ($theme)"
}

# Generate Waybar CSS with current theme
generate_waybar_css() {
    local theme=$1
    source "$THEME_DIR/$theme.conf"
    
    cat > "$CONFIG_DIR/waybar/style.css" << EOF
/* VersionZero Waybar Style - $VZ_THEME_NAME */
/* Auto-generated by theme-switcher.sh */

* {
    font-family: "JetBrainsMono Nerd Font", "Material Design Icons";
    font-size: 13px;
    font-weight: 600;
    min-height: 0;
}

window#waybar {
    background: transparent;
}

#waybar {
    background: $VZ_BACKGROUND_TRANS;
    border: 1.5px solid transparent;
    border-image: $VZ_CSS_BORDER_GRAD 1;
    border-radius: 16px;
    margin: 10px 10px 0 10px;
    padding: 5px 15px;
}

/* Left modules */
#custom-logo {
    color: $VZ_TEXT;
    font-size: 18px;
    margin-right: 15px;
    padding: 0 10px;
    border-radius: 8px;
    background: $VZ_ACCENT_DIM;
}

#custom-logo:hover {
    background: $VZ_ACCENT_BRIGHT;
    transition: all 0.3s cubic-bezier(0.4, 0.0, 0.2, 1);
}

#workspaces {
    margin-right: 10px;
}

#workspaces button {
    color: $VZ_WS_INACTIVE;
    background: transparent;
    border: 1.5px solid $VZ_WS_INACTIVE;
    border-radius: 8px;
    margin: 0 3px;
    padding: 0 10px;
    min-width: 30px;
    transition: all 0.3s ease;
}

#workspaces button.active {
    color: $VZ_TEXT;
    background: $VZ_ACCENT_BRIGHT;
    border-color: $VZ_ACCENT_BRIGHT;
}

#workspaces button:hover {
    background: $VZ_ACCENT_DIM;
    border-color: $VZ_ACCENT_BRIGHT;
}

#workspaces button.urgent {
    background: $VZ_ERROR;
    border-color: $VZ_ERROR;
}

/* Center module */
#clock {
    color: $VZ_TEXT;
    font-size: 16px;
    font-weight: 700;
    padding: 0 20px;
}

/* Right modules */
#tray,
#network,
#pulseaudio,
#battery,
#custom-dashboard {
    color: $VZ_TEXT;
    background: $VZ_ACCENT_DIM;
    border-radius: 8px;
    margin: 0 3px;
    padding: 0 10px;
}

#tray {
    padding: 0 5px;
}

#network {
    padding: 0 12px;
}

#network.disconnected {
    color: $VZ_ERROR;
}

#pulseaudio {
    padding: 0 12px;
}

#pulseaudio.muted {
    color: $VZ_WARNING;
}

#battery {
    padding: 0 12px;
}

#battery.charging {
    color: $VZ_SUCCESS;
}

#battery.warning:not(.charging) {
    color: $VZ_WARNING;
}

#battery.critical:not(.charging) {
    color: $VZ_ERROR;
    animation: blink 1s linear infinite;
}

@keyframes blink {
    50% { opacity: 0.5; }
}

#custom-dashboard {
    font-size: 16px;
    padding: 0 10px;
}

#custom-dashboard:hover {
    background: $VZ_ACCENT_BRIGHT;
    transition: all 0.3s cubic-bezier(0.4, 0.0, 0.2, 1);
}

/* Tooltips */
tooltip {
    background: $VZ_BACKGROUND_TRANS;
    border: 1.5px solid $VZ_ACCENT_BRIGHT;
    border-radius: 8px;
    padding: 10px;
}

tooltip label {
    color: $VZ_TEXT;
}
EOF
}

# Generate EWW CSS with current theme
generate_eww_css() {
    local theme=$1
    source "$THEME_DIR/$theme.conf"
    
    cat > "$CONFIG_DIR/eww/eww.scss" << EOF
/* VersionZero EWW Widgets Style - $VZ_THEME_NAME */
/* Auto-generated by theme-switcher.sh */

\$primary: $VZ_PRIMARY;
\$secondary: $VZ_SECONDARY;
\$accent: $VZ_ACCENT;
\$text: $VZ_TEXT;

\$bg-solid: $VZ_BACKGROUND_SOLID;
\$bg-trans: $VZ_BACKGROUND_TRANS;
\$accent-bright: $VZ_ACCENT_BRIGHT;
\$accent-dim: $VZ_ACCENT_DIM;

\$border-radius: 16px;
\$border-width: 1.5px;

* {
    all: unset;
    font-family: "JetBrainsMono Nerd Font", "Material Design Icons";
}

/* Sidebar Left (Dock) */
.sidebar-left {
    background: \$bg-trans;
    border: \$border-width solid transparent;
    border-image: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(255,255,255,0.1) 100%) 1;
    border-radius: \$border-radius;
    padding: 15px 10px;
}

.dock-icon {
    color: \$text;
    font-size: 24px;
    padding: 12px;
    margin: 8px 0;
    border-radius: 12px;
    background: transparent;
    transition: all 0.3s ease;
}

.dock-icon:hover {
    background: \$accent-dim;
    transform: scale(1.1);
}

.dock-icon.active {
    background: \$accent-bright;
}

/* Sidebar Right (Dashboard) */
.sidebar-right {
    background: \$bg-trans;
    border: \$border-width solid transparent;
    border-image: linear-gradient(180deg, rgba(255,255,255,1) 0%, rgba(255,255,255,0.1) 100%) 1;
    border-radius: \$border-radius;
    padding: 20px;
}

.widget {
    background: rgba(0, 0, 0, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 12px;
    padding: 15px;
    margin: 8px 0;
}

.widget-title {
    color: \$text;
    font-size: 14px;
    font-weight: 600;
    margin-bottom: 10px;
}

.widget-content {
    color: \$text;
    font-size: 12px;
}

/* System monitors */
.monitor-value {
    color: \$accent-bright;
    font-size: 24px;
    font-weight: 700;
}

.monitor-label {
    color: rgba(255, 255, 255, 0.7);
    font-size: 11px;
}

/* Brightness slider */
.brightness-slider scale {
    min-height: 8px;
    min-width: 300px;
}

.brightness-slider trough {
    background: rgba(255, 255, 255, 0.1);
    border-radius: 4px;
    min-height: 8px;
}

.brightness-slider highlight {
    background: $VZ_SLIDER_FILL;
    border-radius: 4px;
}

.brightness-slider slider {
    background: \$text;
    border-radius: 50%;
    min-width: 18px;
    min-height: 18px;
}

/* Quick action buttons */
.quick-button {
    background: \$accent-dim;
    border: 1px solid \$accent-bright;
    border-radius: 8px;
    padding: 10px 15px;
    color: \$text;
    font-size: 12px;
    transition: all 0.2s ease;
}

.quick-button:hover {
    background: \$accent-bright;
    transform: scale(1.05);
}

.quick-button.active {
    background: \$accent-bright;
    border-color: \$text;
}
EOF
}

# Generate Mako config with current theme
generate_mako_config() {
    local theme=$1
    source "$THEME_DIR/$theme.conf"
    
    cat > "$CONFIG_DIR/mako/config" << EOF
# VersionZero Mako Notifications - $VZ_THEME_NAME
# Auto-generated by theme-switcher.sh

font=JetBrainsMono Nerd Font 11
background-color=$VZ_BACKGROUND_TRANS
text-color=$VZ_TEXT
border-color=$VZ_ACCENT_BRIGHT
border-size=2
border-radius=12
padding=15
margin=10
width=350
height=120

default-timeout=5000
ignore-timeout=0

[urgency=low]
border-color=$VZ_INFO

[urgency=normal]
border-color=$VZ_ACCENT_BRIGHT

[urgency=critical]
border-color=$VZ_ERROR
default-timeout=0
EOF
}

# Generate terminal configs with current theme
generate_terminal_configs() {
    local theme=$1
    source "$THEME_DIR/$theme.conf"
    
    # Alacritty TOML
    cat > "$CONFIG_DIR/alacritty/colors.toml" << EOF
# VersionZero Alacritty Colors - $VZ_THEME_NAME
# Auto-generated by theme-switcher.sh
# Include this in your main alacritty.toml with: import = ["~/.config/alacritty/colors.toml"]

[colors.primary]
background = "$VZ_TERM_BLACK"
foreground = "$VZ_TERM_WHITE"

[colors.normal]
black = "$VZ_TERM_BLACK"
red = "$VZ_TERM_RED"
green = "$VZ_TERM_GREEN"
yellow = "$VZ_TERM_YELLOW"
blue = "$VZ_TERM_BLUE"
magenta = "$VZ_TERM_MAGENTA"
cyan = "$VZ_TERM_CYAN"
white = "$VZ_TERM_WHITE"

[colors.bright]
black = "$VZ_TERM_BRIGHT_BLACK"
red = "$VZ_TERM_BRIGHT_RED"
green = "$VZ_TERM_BRIGHT_GREEN"
yellow = "$VZ_TERM_BRIGHT_YELLOW"
blue = "$VZ_TERM_BRIGHT_BLUE"
magenta = "$VZ_TERM_BRIGHT_MAGENTA"
cyan = "$VZ_TERM_BRIGHT_CYAN"
white = "$VZ_TERM_BRIGHT_WHITE"
EOF
    
    echo "✓ Terminal configs generated"
}

# Main logic
case "${1:-next}" in
    theme1|theme2|theme3)
        apply_theme "$1"
        ;;
    next)
        next_theme=$(get_next_theme)
        apply_theme "$next_theme"
        ;;
    *)
        echo "Usage: $0 [theme1|theme2|theme3|next]"
        echo "  theme1 - Midnight Elegance"
        echo "  theme2 - Ocean Breeze"
        echo "  theme3 - Cyberpunk Dreams"
        echo "  next   - Cycle to next theme (default)"
        exit 1
        ;;
esac